export const ADD_PRODUCT = 'ADD_PRODUCT';
export const INCREASE_PRODUCT_COUNT = "INCREASE_PRODUCT_COUNT";
export const DECREASE_PRODUCT_COUNT = "DECREASE_PRODUCT_COUNT";
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const COMPLETE_PRODUCT = 'COMPLETE_PRODUCT';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const ADD_LIST = "ADD_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const SET_LIST_ACTIVE = "SET_LIST_ACTIVE";
