export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const COMPLETE_PRODUCT = 'COMPLETE_PRODUCT';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';